# Generated by Django 2.2.3 on 2019-07-21 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Full Name')),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Book Title')),
                ('description', models.TextField(verbose_name='Book Description')),
                ('count', models.PositiveIntegerField(verbose_name='Book Count')),
                ('subscription_cost', models.PositiveIntegerField(verbose_name='Subscription Cost')),
                ('topic', models.CharField(max_length=20, verbose_name='Book Topic')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Full Name')),
                ('address', models.CharField(max_length=512, verbose_name='Address')),
                ('phone', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscriber',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_date', models.DateField(auto_now_add=True)),
                ('amount_pad', models.PositiveIntegerField(verbose_name='Amount Paid')),
                ('returned', models.BooleanField(verbose_name='Book Returned?')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Book')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Subscriber')),
            ],
        ),
    ]
